beginning framework for making 3D profiles for LE3 from M3DC1 data

diff --git a/le3/bin/le3 b/le3/bin/le3
--- a/le3/bin/le3
+++ b/le3/bin/le3
@@ -32,6 +32,12 @@ then
   echo
   echo "         -g <template>"
   echo "         Copy <template> into simulation path."
+  echo
+  echo "3D GEOMETRY AND PROFILE GENERATION"
+  echo
+  echo "         -profile -i <rz and profile netcdf file>"
+  echo "         Run PROFILES_3D using input.profiles_3d in <simdir>."
+  echo           
 
   exit 1
 fi
@@ -47,6 +53,8 @@ NPROC=1
 # Execute/test mode flags
 EXEC_FLAG=0
 GENERATE_FLAG=0
+PROFILE_FLAG=0
+FILE_FLAG=0
 #=============================================================
 
 #=============================================================
@@ -60,6 +68,10 @@ while [ $# -gt 0 ] ; do
   -e) shift ; LOCDIR=$1 ; EXEC_FLAG=1 ;;
 
   -g) shift ; LOCDIR=$1 ; GENERATE_FLAG=1 ;;
+
+  -profile) PROFILE_FLAG=1 ;;
+
+  -i) shift ; FILE_FLAG=1 ; FILE=$1 ;;
 
   *) echo "ERROR: incorrect le3 syntax." ; exit 1 ;;
  
@@ -90,6 +102,26 @@ then
    else
       cp -ai ${LE3_DIR}/tools/input/$LOCDIR $SIMDIR
    fi
+   exit 0
+fi
+#============================================================
+
+#============================================================
+# Generate 3d profiles -profile set, then exit.
+#
+if [ $PROFILE_FLAG -eq 1 ]
+then
+   cd $SIMDIR
+   if [ "$FILE" == "" ] ; then
+   echo "ERROR: (profiles_3d) Specify an input file via -i."
+   exit 1
+   fi
+
+   python $LE3_DIR/bin/profiles_3d_parse.py 
+   cp $FILE input.profiles_3d.rz.nc
+   $LE3_DIR/profiles_3d/profiles_3d
+   rm input.profiles_3d.rz.nc
+   echo "not yet working"
    exit 0
 fi
 #============================================================
