profiles_gen now includes DSKGATO read capability.

diff --git a/shared/bin/profiles_gen b/shared/bin/profiles_gen
--- a/shared/bin/profiles_gen
+++ b/shared/bin/profiles_gen
@@ -123,7 +123,7 @@ then
    echo "             Specify Corsica data file."
    echo
    echo "             -g <gfile>"
-   echo "             Merge EFIT gfile for high-precision geometry data."
+   echo "             GFILE (geqdsk) containing flux-surface data [required]."
    echo 
    echo "             -nfourier <gfile>"
    echo "             Number of Fourier modes to retain in input.profiles.geo/input.geo."
@@ -155,19 +155,18 @@ then
    echo
    echo "PEQDSK/PFILE Options"
    echo
-   echo "             -i <data.peq>"
-   echo "             Specify ELITE pfile data file."
+   echo "             -i <PFILE>"
+   echo "             Specify PFILE (peqdsk) data file."
    echo
    echo "             -g <gfile>"
-   echo "             Merge EFIT gfile for high-precision geometry data."
-   echo "             [This is required for pfiles]"
+   echo "             GFILE (geqdsk) containing flux-surface data [required]."
    echo 
    echo "             -nfourier <gfile>"
    echo "             Number of Fourier modes to retain in input.profiles.geo/input.geo."
    echo
    echo "ASTRA Options"
    echo
-   echo "             -i <data.astra>"
+   echo "             -i <data>"
    echo "             Specify ASTRA data file."
    echo
    echo "             -m <map file>"
@@ -182,8 +181,8 @@ then
    echo "             -i null"
    echo "             Toggle null profile data mode."
    echo
-   echo "             -g <gfile>"
-   echo "             Merge EFIT gfile for high-precision geometry data [required]."
+   echo "             -g <GFILE>"
+   echo "             GFILE (geqdsk) containing flux-surface data [required]."
    echo 
    echo "             -nfourier <gfile>"
    echo "             Number of Fourier modes to retain in input.profiles.geo/input.geo."
@@ -208,10 +207,10 @@ then
    echo "             -i <data>"
    echo "             Data in input.profiles format."
    echo
-   echo "             -g <gfile>"
-   echo "             EFIT gfile."
+   echo "             -g <GFILE>"
+   echo "             GFILE (geqdsk) containing flux-surface data."
    echo 
-   echo "             -nfourier <gfile>"
+   echo "             -nfourier <GFILE>"
    echo "             Number of Fourier modes to retain in input.profiles.geo/input.geo."
    echo
    echo "             -gmerge"
@@ -465,9 +464,11 @@ while [ $# -gt 0 ] ; do
   esac
   shift
 done
-
 #=============================================================
 
+#=============================================================
+# Construct simulation directory: $SIMDIR
+#
 if [ "$LOCDIR" == "." ]
 then
    LOCDIR=`basename $PWD`
@@ -476,6 +477,50 @@ fi
 SIMDIR=$SIMROOT/$LOCDIR
 
 cd $SIMDIR
+#=============================================================
+
+#=============================================================
+# Filetype detection and management
+#
+if [ $CREATE_FLAG -eq 0 ] ; then 
+
+   if [ "$FILE" == "" ] ; then
+      echo "ERROR: (profiles_gen) Specify an input file via -i."
+      exit 1
+   fi
+
+   itype=`gacode_type_autodetect $FILE`
+
+   if [ "$itype" == "NOT_FOUND" ] ; then
+      echo "ERROR: (profiles_gen) $FILE not found."
+      exit 1
+   fi
+   if [ "$itype" == "UNKNOWN" ] ; then
+      echo "ERROR: (profiles_gen) $FILE is an unknown type."
+      exit 1 
+   fi
+
+fi
+
+if [ $G_FLAG -eq 1 ] ; then
+
+   gtype=`gacode_type_autodetect $GFILE`
+   echo "INFO: (profiles_gen) $GFILE is autodetected as $gtype."
+
+else
+
+   gtype=none
+   if [ "$itype" == "PFILE" ] ; then
+      echo "ERROR: (profiles_gen) A GFILE (-g) must be used with a PFILE."  
+      exit 1
+   fi
+   if [ "$itype" == "CORSICA" ] ; then
+      echo "ERROR: (profiles_gen) A GFILE (-g) must be used with a CORSICA file."  
+      exit 1
+   fi
+
+fi
+#=============================================================
 
 #=============================================================
 # Manage CREATE MODE
@@ -497,9 +542,11 @@ then
       cp $FILE.save input.profiles
       echo "INFO: (profiles_gen) Keeping backup of $FILE in $FILE.save"
       python $GACODE_ROOT/shared/bin/profile_parse.py $FILE
+      echo "INFO: (profiles_gen) Modifying $FILE."
    else
       rm -f input.profiles input.profiles.gen
       FILE=input.profiles
+      echo "INFO: (profiles_gen) Creating $FILE."
    fi
    # Run create
    touch input.create
@@ -518,13 +565,7 @@ fi
 #=============================================================
 # Managing input file (also catches UFILE mode)
 
-if [ $FILE_FLAG -eq 0 ] ; then
-
-  # No file!
-  echo "ERROR: (profiles_gen) Please specify an input file with -i <file>"
-  exit 1 
-
-elif [ "$FILE" == "UFILE" ] ; then
+if [ "$itype" == "UFILE" ] ; then
 
    #-----------------------------------------------
    # UFILE mode
@@ -542,40 +583,24 @@ elif [ "$FILE" == "UFILE" ] ; then
       exit 1
    fi
 
-elif [ "$FILE" == "null" ] ; then
+elif [ "$itype" == "null" ] ; then
 
    # gfile-only mode
-   echo "INFO: (profiles_gen) Parsing gfile only"
-
-elif [ ! -f $FILE ] ; then
-
-   # bad filename
-   echo "ERROR: (profiles_gen) $FILE not found"
-   exit 1 
+   echo "INFO: (profiles_gen) Parsing GFILE only."
 
 else
 
-   echo "INFO: (profiles_gen) $FILE found"
+   echo "INFO: (profiles_gen) $FILE is autodetected as $itype."
 
 fi
 
 #=============================================================
 # Trap a p-file and split into components 
 #
-type=`gacode_type_autodetect $FILE`
-if [[ "$type" == *PFILE* ]]
-then
-   echo "INFO: (profiles_gen) Detected pfile format."
-   # First, ensure gfile exists too.
-   if [ $G_FLAG -eq 0 ] 
-   then
-     echo "ERROR: (profiles_gen) You must supplement the pfile with a gfile (use -g)."
-     exit 1
-   fi
+if [ "$itype" == "PFILE" ] ; then
    # Now, strip pfile into parts.  Rename $FILE so pfile detected in prgen.
    rm -f pfile.*
    python $GACODE_ROOT/shared/bin/gacode_pfile_tool.py $FILE
-   FILE=dummy.peq
 fi
 #=============================================================
 
@@ -752,11 +777,8 @@ fi
 #=============================================================
 # Check for executable
 #
-if [ ! -f $EXEC ]
-then
-   echo "You must first build the executable:"
-   echo " "
-   echo "> cd $GYRO_DIR/tools ; make" 
+if [ ! -f $EXEC ] ; then
+   echo "ERROR: (profiles_gen) Did not find executable $EXEC."
    exit 1
 fi
 #=============================================================
@@ -764,8 +786,7 @@ fi
 #=============================================================
 # Construct prgen input file ($CONFIG)
 #
-type=`gacode_type_autodetect $GFILE`
-if [[ "$type" == *DSKGATO* ]] ; then
+if [[ "$gtype" == *DSKGATO* ]] ; then
    EFIT_METHOD=4
 else
    EFIT_METHOD=$(($G_FLAG+$OMFIT_FLAG+1))
@@ -775,6 +796,7 @@ date > $CONFIG
 
 # Required data file (ITERDB, PLASMASTATE, etc)
 echo $FILE >> $CONFIG
+echo $itype >> $CONFIG
 
 # Optional CER file
 echo $CER_FILE >> $CONFIG
