Reviving tgyro_plot functionality, with analogy to gyro_plot.

diff --git a/tgyro/bin/tgyro_plot b/tgyro/bin/tgyro_plot
--- a/tgyro/bin/tgyro_plot
+++ b/tgyro/bin/tgyro_plot
@@ -3,7 +3,7 @@
 # tgyro_plot
 #
 # PURPOSE:
-#  Handles plotting of tgyro output
+#  Plotting/listing routines for TGYRO output.
 #==============================================================================
 
 #==============================================================================
@@ -13,56 +13,55 @@ n=$#
 
 if [ $n -eq 0 ]
 then
-   echo
-   echo "Usage:   tgyro_plot [options]"
-   echo
-   echo "         tgyro_plot provides primitive plotting routines for output"
-   echo "         from tgyro through python and matplotlib.  The acquisition"
-   echo "         and storage of data is handled through a python class called"
-   echo "         TGYROData, which is automatically called when this script is"
-   echo "         run."
-   echo
-   echo "         -l <path>"
-   echo "         Loads all output files in specified directory.  If no"
-   echo "         directory is given, then the current working directory is"
-   echo "         used."
-   echo
-   echo "         -p <options>"
-   echo "         Opens python for editing with specified directory loaded, and"
-   echo "         creates requested summary plots.  Options are:"
-   echo "             Typing 'ps' after '-p' creates a profile summary plot."
-   echo "             gs creates a gradient summary plot"
-   echo "             cs creates a chi-value summary plot"
-   echo "             fs creates an energy flux summary plot"
-   echo "             ms creates a momentum flux summary plot"
-   echo "         If no options are specified, then the python shell opens with"
-   echo "         no plots created by default.  There is no limit to the number"
-   echo "         of summary plots that may be specified after -p.  After the"
-   echo "         shell has loaded, type 'help(TGYROData)' for information on"
-   echo "         how to create plots with python."
-   echo "         Typing 'help(plt)' is also useful, but can be a little"
-   echo "         overwhelming.  The online help for matplotlib is much better"
-   echo "         organized, and searchable as well.  At time of creation of"
-   echo "         this file, the website for matplotlib was:"
-   echo "         http://matplotlib.sourceforge.net/"
-   echo ""
+  echo
+  echo "Usage:    tgyro_plot [options]"
+  echo
+  echo "          -p <path>"
+  echo "          Set optional path to simulation directory."
+  echo "          [The default path is the current directory]"
+  echo
+  echo "          -e <simdir>"
+  echo "          Use data in <simdir>."
+  echo 
+  echo "          -f <filetype>"
+  echo "          Output file type."
+  echo "           <filetype>=emf, eps, pdf, png, ps, raw, rgba, svg, svgz"
+  echo 
+  echo "          -field <value>"
+  echo "          Specify field to be plotted: [0,n_field-1]."
+  echo "          Alternatively, specifying 's' returns a sum of all fields (default=s)."
+  echo
+  echo "          -kinetic <value>"
+  echo "          Specify species to be plotted: [0,n_kinetic-1]."
+  echo
+  echo "          -moment <value>"
+  echo "          Specify moment to be plotted: [0,3] (default=1)"
+  echo
+  echo "          -plot <type>"
+  echo "          Generate plot of given type."
+  echo "          If this keyword is omitted, data will be listed to the screen."
+  echo "           <type> = flux_tot,"
+  echo
+  echo "Example:"
+  echo
+  echo "   tgyro_plot -e . -plot flux_tot"
 
-exit 1
+  exit 1
 fi
+#==============================================================================
 
 #==============================================================================
 # Define variables for flag capture
 #
-# Default output directory
-PLOT_DIR=$PWD
-N1=1
-N2=1
-# Plot mode flags
-LOAD_FLAG=0
-LINE_FLAG=0
-VERBOSE_FLAG=0
-LEGEND_FLAG=0
-PLOT_STRING=""
+# Default simulation directory
+LOCDIR=.
+SIMROOT=$PWD
+PLOT_TYPE=
+DIFF_FLAG=0
+I_KINETIC=0
+I_FIELD="s"
+I_MOMENT=0
+FTYPE=screen
 #==============================================================================
 
 #==============================================================================
@@ -71,36 +70,45 @@ PLOT_STRING=""
 while [ $# -gt 0 ] ; do
   case "$1" in
 
-  -l) shift ; PLOT_DIR=$1 ; shift ;;
+  -plot) shift ; PLOT_TYPE=$1 ;;
+  
+  -e) shift ; LOCDIR=$1 ;;
 
-  -p) shift ; LINE_FLAG=1 ; PLOT_STRING="$1" ; shift ; break ;;
+  -p) shift ; SIMROOT=$1 ;;
 
-  -dim) shift ; N1=$1 ; shift ; N2=$1 ; shift ;;
+  -kinetic) shift ; I_KINETIC=$1 ;;
 
-  -v) shift ; VERBOSE_FLAG=1 ;;
+  -field) shift ; I_FIELD=$1 ;;
 
-  -s) shift ; LEGEND_FLAG=0 ;;
+  -moment) shift ; I_MOMENT=$1 ;;
 
-  *) echo "ERROR: incorrect syntax." ; exit 1 ;;
+  -f) shift ; FTYPE=$1 ;;
+
+  *) echo "ERROR: incorrect tgyro_plot syntax." ; exit 1 ;;
 
   esac
+  shift
 done
 #==============================================================================
-# Plot data
 
-if [ $LINE_FLAG -eq 1 ]
+if [ "$LOCDIR" == "." ]
 then
-  while [ $# -gt 0 ]
-  do
-    PLOT_STRING="$PLOT_STRING $1"
-    shift
-  done
-  if [ "$PLOT_STRING" != "" ]
-  then
-    python ~/gacode/shared/python/pyrats/tgyro/interpreter.py $PLOT_DIR $N1 $N2 $VERBOSE_FLAG $LEGEND_FLAG $PLOT_STRING &
-    exit 0
-  else
-    python -i ~/gacode/shared/python/pyrats/tgyro/interpreter.py $PLOT_DIR $N1 $N2 $VERBOSE_FLAG $LEGEND_FLAG $PLOT_STRING
-    exit 0
-  fi
+   LOCDIR=`basename $PWD`
+   cd .. ; SIMROOT=$PWD
 fi
+SIMDIR=$SIMROOT/$LOCDIR
+cd $SIMDIR
+
+PYROOT=$GACODE_ROOT/shared/python/pyrats/tgyro
+
+#==============================================================================
+# Display diff if -ldiff set, then exit.
+#
+case "$PLOT_TYPE" in
+
+   flux_tot)  
+	python $PYROOT/flux_tot.py $SIMDIR $FTYPE & ;;
+
+esac 
+
+exit 0
